### ISSUE TITLE
CT converting circular structure to JSON

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#83]
```
number-line-operations : build
Build failed with status code 3:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (number-line-operations, brands: phet)
Building brand: phet
Fatal error: Converting circular structure to JSON
--> starting at object with constructor 'NormalModule'
| property 'dependencies' -> object with constructor 'Array'
| index 0 -> object with constructor 'HarmonyCompatibilityDependency'
--- property 'originModule' closes the circle

Webpack build errors: [
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../phetcommon/js/util/StringUtils.js' in '/data/share/phet/continuous-testing/ct-snapshots/1610429993597/number-line-operations/js/common'
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/lib/Compilation.js:925:10
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/lib/NormalModuleFactory.js:401:22
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/lib/NormalModuleFactory.js:130:21
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/lib/NormalModuleFactory.js:224:22
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/neo-async/async.js:2830:7
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/neo-async/async.js:6877:13
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/lib/NormalModuleFactory.js:214:25
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (<anonymous>:15:1)
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (<anonymous>:15:1)
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (<anonymous>:27:1)
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (<anonymous>:16:1)
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (<anonymous>:16:1)
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (<anonymous>:16:1)
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5
at eval (<anonymous>:15:1)
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
at /data/share/phet/continuous-testing/ct-snapshots/1610429993597/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
at processTicksAndRejections (internal/process/task_queues.js:75:11)

resolve '../../../../phetcommon/js/util/StringUtils.js' in '/data/share/phet/continuous-testing/ct-snapshots/1610429993597/number-line-operations/js/common'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1610429993597/number-line-operations/package.json (relative path: ./js/common)
Field 'browser' doesn't contain a valid alias configuration
No description file found
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phetcommon/js/util/StringUtils.js doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phetcommon/js/util/StringUtils.js.wasm doesn't exist
.mjs
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phetcommon/js/util/StringUtils.js.mjs doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phetcommon/js/util/StringUtils.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phetcommon/js/util/StringUtils.js.json doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/phetcommon/js/util/StringUtils.js doesn't exist
]
Snapshot from 1/11/2021, 10:39:53 PM
```

**Comment by jbphet** [comment]
This was due to a bad include path, and it's weird that the sim even loaded.  It's fixed.  Closing.
