### ISSUE TITLE
CT reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-line-operations#97]
```
number-line-operations : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/number-line-operations/number-line-operations_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-operations%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649677381343%22%2C%22timestamp%22%3A1649684338576%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=300, oldValue=400
Error: Assertion failed: reentry detected, value=300, oldValue=400
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/assert/js/assert.js:25:13)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/axon/js/Property.js:216:15)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/axon/js/Property.js:147:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/number-line-operations/js/common/model/OperationTrackingNumberLine.js:113:36
at Array.forEach (<anonymous>)
at updateEndpoints (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/number-line-operations/js/common/model/OperationTrackingNumberLine.js:98:23)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/axon/js/Multilink.js:46:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/axon/js/Property.js:218:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649677381343/chipper/dist/js/axon/js/Property.js:147:14)
id: Bayes Chrome
Snapshot from 4/11/2022, 5:43:01 AM
```

**Comment by jbphet** [comment]
This problem has not occurred during at least the last 29 runs of CT, which is all we have a record for on CT.  This is around 48 hours of testing.  It also did not occur during 15 minutes of local  pan-and-zoom-fuzz testing on the unbuilt version, which is the configuration identified by CT.  I'll watch CT for a week or so and see if it recurs, and if so, I'll put some more time into tracking it down.  If not, I'll assume it was something transient in common code and will close.

**Comment by jbphet** [comment]
I've been checking CT every day for a week (excluding the weekend), and haven't seen this.  I'm going to assume it was something transient in common code.  Closing.
